In [52]:
import numpy as np

In [53]:
mat = np.matrix(
    [[1,2,1],
    [4,2,13],
    [7,8,1],
    [8,4,5]]
).T

In [54]:
mat_mean_dev = np.matrix(
    [[-4,-2,-4],
    [-1,-2,8],
    [2,4,-4],
    [3,0,0]]
).T
mat_mean_dev

matrix([[-4, -1,  2,  3],
        [-2, -2,  4,  0],
        [-4,  8, -4,  0]])

# SVD

In [70]:
mat*mat.T

matrix([[130,  98, 100],
        [ 98,  88,  56],
        [100,  56, 196]])

In [55]:
u, sigma, v =np.linalg.svd(mat_mean_dev)

In [56]:
u

matrix([[ 0.07404999,  0.8192675 , -0.56861003],
        [ 0.30300421,  0.52473595,  0.79551281],
        [-0.95010791,  0.23119895,  0.20938481]])

In [57]:
sigma

array([10.18105956,  6.44429148,  2.1947969 ])

In [58]:
v

matrix([[ 0.28466814, -0.81336541,  0.50687735,  0.02181993],
        [-0.81488208, -0.00297128,  0.43646117,  0.3813922 ],
        [-0.07022278,  0.29736825,  0.55007   , -0.77721547],
        [ 0.5       ,  0.5       ,  0.5       ,  0.5       ]])

# Find PCA

In [59]:
covariance = np.cov(mat_mean_dev)

In [60]:
covariance

array([[10.,  6.,  0.],
       [ 6.,  8., -8.],
       [ 0., -8., 32.]])

In [64]:
eigvalue, eigvector = np.linalg.eig(covariance)


In [65]:
eigvalue

array([ 1.60571114, 13.84296424, 34.55132462])

In [69]:
eigvector.T

array([[-0.56861003,  0.79551281,  0.20938481],
       [-0.8192675 , -0.52473595, -0.23119895],
       [-0.07404999, -0.30300421,  0.95010791]])